// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPB64_BDLnVrtTpiUJwsGXQqCPbyOw0Io',
    appId: '1:819509773689:web:b11c2f8395e2d396581ba8',
    messagingSenderId: '819509773689',
    projectId: 'scalp-18928',
    authDomain: 'scalp-18928.firebaseapp.com',
    databaseURL: 'https://scalp-18928-default-rtdb.firebaseio.com',
    storageBucket: 'scalp-18928.firebasestorage.app',
    measurementId: 'G-RWL5LVSQVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09rYwm9JJ5zHwcrAZYvBcT6H-9gfk_ZI',
    appId: '1:819509773689:android:fc1503e2446c8f99581ba8',
    messagingSenderId: '819509773689',
    projectId: 'scalp-18928',
    databaseURL: 'https://scalp-18928-default-rtdb.firebaseio.com',
    storageBucket: 'scalp-18928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLc8_xv6Wdcg4TTs4nAB1YTRi8HUxQlKY',
    appId: '1:819509773689:ios:2785b775ad98cc30581ba8',
    messagingSenderId: '819509773689',
    projectId: 'scalp-18928',
    databaseURL: 'https://scalp-18928-default-rtdb.firebaseio.com',
    storageBucket: 'scalp-18928.firebasestorage.app',
    iosClientId: '819509773689-gakpf56brfmhluplv3176qn7bu2q97uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.scalpMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLc8_xv6Wdcg4TTs4nAB1YTRi8HUxQlKY',
    appId: '1:819509773689:ios:2785b775ad98cc30581ba8',
    messagingSenderId: '819509773689',
    projectId: 'scalp-18928',
    databaseURL: 'https://scalp-18928-default-rtdb.firebaseio.com',
    storageBucket: 'scalp-18928.firebasestorage.app',
    iosClientId: '819509773689-gakpf56brfmhluplv3176qn7bu2q97uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.scalpMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPB64_BDLnVrtTpiUJwsGXQqCPbyOw0Io',
    appId: '1:819509773689:web:d32571ae80f34288581ba8',
    messagingSenderId: '819509773689',
    projectId: 'scalp-18928',
    authDomain: 'scalp-18928.firebaseapp.com',
    databaseURL: 'https://scalp-18928-default-rtdb.firebaseio.com',
    storageBucket: 'scalp-18928.firebasestorage.app',
    measurementId: 'G-7GVWMEGSGZ',
  );

}